(ns constants)

(def name "Liam Duffy")
(def charset "UTF-8")
(def viewport-content "width=device-width, initial-scale=1")
(def tailwind-styles-path "./tailwind.css")
(def script-path "./script.js")
(def favicon-emoji "✨")
(def favicon-svg (str "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%2210 0 100 100%22><text y=%22.90em%22 font-size=%2290%22>" favicon-emoji "</text></svg>"))
(def fonts-google-api-url "https://fonts.googleapis.com")
(def fonts-google-static-url "https://fonts.gstatic.com")
(def fonts-jetbrains-url "https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital@0;1&display=swap")
(def flowcode-url "https://www.flowcode.com")
(def social-star-url "https://socialstar.co")
(def thejuggernaut-url "https://www.thejuggernaut.com")