name: Build site

on:
  push:
    branches:
      - main

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Babashka
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: 1.3.186

      - name: Run build script
        run: bb scripts/build.bb