name: Build and deploy site

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - uses: turtlequeue/setup-babashka@v1.5.0
        with:
            babashka-version: 1.3.186
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: |
          bun install
          bb build.bb
          yarn vercel deploy build/prod --prod --token=${{ secrets.VERCEL_TOKEN }} 